#!/usr/bin/env node
/**
 * Seed real manga data from Jikan API (MyAnimeList)
 * Usage: node scripts/seed-jikan.mjs
 * Output: supabase/migrations/007_real_data.sql
 */

import { writeFileSync } from "fs";
import { join } from "path";

const JIKAN = "https://api.jikan.moe/v4";

// MAL ID → our series slug
const SERIES = [
  { malId: 13,     slug: "one-piece",          publisher: "panini" },
  { malId: 42,     slug: "dragon-ball",         publisher: "star-comics" },
  { malId: 11,     slug: "naruto",              publisher: "panini" },
  { malId: 23390,  slug: "attack-on-titan",     publisher: "panini" },
  { malId: 2,      slug: "berserk",             publisher: "panini" },
  { malId: 12,     slug: "bleach",              publisher: "star-comics" },
  { malId: 25,     slug: "fullmetal-alchemist", publisher: "panini" },
  { malId: 21,     slug: "death-note",          publisher: "panini" },
  { malId: 26,     slug: "hunter-x-hunter",     publisher: "panini" },
  { malId: 119161, slug: "spy-x-family",        publisher: "panini" },
  { malId: 116778, slug: "chainsaw-man",        publisher: "panini" },
  { malId: 113138, slug: "jujutsu-kaisen",      publisher: "panini" },
  { malId: 96792,  slug: "demon-slayer",        publisher: "panini" },
  { malId: 642,    slug: "vinland-saga",        publisher: "jpop" },
  { malId: 56805,  slug: "a-silent-voice",      publisher: "jpop" },
  { malId: 85781,  slug: "dungeon-meshi",       publisher: "jpop" },
  { malId: 91941,  slug: "made-in-abyss",       publisher: "jpop" },
  { malId: 4632,   slug: "goodnight-punpun",    publisher: "jpop" },
  { malId: 107931, slug: "blue-period",         publisher: "jpop" },
  { malId: 664,    slug: "akira",               publisher: "jpop" },
];

function sqlStr(val) {
  if (val === null || val === undefined) return "NULL";
  return "'" + String(val).replace(/'/g, "''") + "'";
}

function sleep(ms) {
  return new Promise(r => setTimeout(r, ms));
}

async function fetchManga(malId, retries = 3) {
  for (let attempt = 0; attempt < retries; attempt++) {
    const res = await fetch(`${JIKAN}/manga/${malId}`);
    if (res.status === 429) {
      const wait = 3000 * (attempt + 1);
      console.log(`  Rate limited, waiting ${wait}ms...`);
      await sleep(wait);
      continue;
    }
    if (!res.ok) throw new Error(`Jikan ${malId}: ${res.status}`);
    const json = await res.json();
    return json.data;
  }
  throw new Error(`Jikan ${malId}: too many rate limit retries`);
}

async function main() {
  const sql = [];
  sql.push("-- Takobon — Real manga data from MyAnimeList via Jikan API");
  sql.push("-- Auto-generated by scripts/seed-jikan.mjs");
  sql.push("");

  for (const entry of SERIES) {
    console.log(`Fetching ${entry.slug} (MAL #${entry.malId})...`);

    let manga;
    try {
      manga = await fetchManga(entry.malId);
    } catch (e) {
      console.warn(`  Failed: ${e.message}`);
      continue;
    }

    const coverUrl = manga.images?.jpg?.large_image_url ?? manga.images?.jpg?.image_url ?? null;
    const titleEn = manga.title_english ?? manga.title;
    const titleJp = manga.title;
    const volumes = manga.volumes ?? 0;
    const status = manga.status === "Finished" ? "completed" : manga.status === "Discontinued" ? "cancelled" : "ongoing";
    const startYear = manga.published?.from ? new Date(manga.published.from).getFullYear() : null;
    const synopsis = manga.synopsis
      ? manga.synopsis.replace(/\[Written by MAL Rewrite\]/g, "").replace(/\n+/g, " ").trim().slice(0, 800)
      : null;

    console.log(`  ${titleEn} — ${volumes} volumes, ${status}`);

    // Update series metadata
    sql.push(`-- ${titleEn}`);
    if (coverUrl) {
      sql.push(`update series set cover_url = ${sqlStr(coverUrl)} where slug = '${entry.slug}';`);
    }
    if (synopsis) {
      sql.push(`update series set description_it = ${sqlStr(synopsis)} where slug = '${entry.slug}';`);
    }
    if (startYear) {
      sql.push(`update series set start_year = ${startYear} where slug = '${entry.slug}';`);
    }
    sql.push(`update series set status = '${status}' where slug = '${entry.slug}';`);
    sql.push("");

    // Insert volumes
    if (volumes > 0) {
      sql.push(`-- Volumes for ${entry.slug}`);
      for (let i = 1; i <= volumes; i++) {
        // Estimate Italian release: start_year + ~3 months per volume
        const releaseYear = startYear ? startYear + Math.floor((i - 1) / 4) : null;
        const releaseMonth = releaseYear ? ((((i - 1) % 4) * 3) + 1) : null;
        const releaseDate = releaseYear ? `${releaseYear}-${String(releaseMonth).padStart(2, "0")}-01` : null;
        const price = entry.slug === "berserk" ? 8.50 : entry.slug === "akira" ? 15.00 : 5.90;

        sql.push(`insert into volumes (series_id, number, cover_url, release_date_it, cover_price_eur)`);
        sql.push(`select id, ${i}, ${sqlStr(coverUrl)}, ${releaseDate ? sqlStr(releaseDate) : "NULL"}, ${price}`);
        sql.push(`from series where slug = '${entry.slug}'`);
        sql.push(`on conflict (series_id, number) do update set cover_url = excluded.cover_url;`);
      }
      sql.push("");
    }

    // Jikan rate limit: 1 req/sec sustained
    await sleep(1500);
  }

  const output = sql.join("\n");
  const outPath = join(process.cwd(), "supabase/migrations/007_real_data.sql");
  writeFileSync(outPath, output, "utf8");

  console.log("\n✅ Done! Run supabase/migrations/007_real_data.sql in your Supabase SQL Editor.");
}

main().catch(e => { console.error(e); process.exit(1); });
